<?php

/**
 * @file
 * A global module that injects html into the top of each page.
 */

function inject_header_page_build(&$page) {
  drupal_set_message("build hook called");
  $page['page_top']['custom_header'] = array(
    "#markup" => t(<<<HTML
<div class='top-bar'>
  <b>This HTML Was Injected!</b>
</div>
<style>
  .top-bar {
    color: white;
    padding: 15px;
    margin: 15px;
    text-align: center;
    font-size: 1.5em;
  }
</style>"
HTML
),
    "#weight" => 20
  );
}

function inject_header_help($path, $arg) {
  switch ($path) {
    case "admin/help#inject_header":
      return t("does things"); 
      break; 
  }
}
?>
