<?php

/**
 * @file
 * A global module that injects html into the top of each page.
 */

function inject_header_page_build(&$page) {
  global $theme;

  if(!preg_match('/^admin\/.?/', current_path()) && $theme == 'base7') {
    $page['page_top']['custom_header'] = array(
      "#markup" => t(
<<<HTML
<div class='inject-header'>
<b>This HTML Was Injected!</b>
</div>
HTML
      ),
      "#weight" => 20
    );

    $page['page_top']['custom_header']['#attached']['js'] = array(
      drupal_get_path('module', 'inject_header') . '/inject_header.js'
    );

    $page['page_top']['custom_header']['#attached']['css'] = array(
      drupal_get_path('module', 'inject_header') . '/inject_header.css'
    );
  }
}

function inject_header_help($path, $arg) {
  switch ($path) {
    case "admin/help#inject_header":
      return t("does things");
      break;
  }
}
?>
